volkswagen_id_set_climatisation:
  name: Volkswagen ID Set Climatisation
  description: Sets climatisation in Volkswagen ID cars.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: WVGZZZA1ZMP001337
      selector:
        text:
    start_stop:
      name: Start or Stop
      description: Starts or stops climatisation.
      required: true
      selector:
        select:
          options:
            - "start"
            - "stop"
    target_temp:
      name: Target Temperature.
      description: Sets target temperature in celsius.
      required: false
      selector:
        number:
          min: 10
          max: 30
